### ISSUE TITLE
initial code review

### ISSUE THREAD

**Issue by richm** [andyprice/gfs2-role#1]
You should run `ansible-lint` against your code e.g.
`tox -e ansible-lint`
and
`tox -e collection,ansible-lint`

If you have questions about how to address a particular linter issue, let me know.  Many of the issues I will list below will also be flagged by ansible-lint

All .yml files should have `---` as the first line (can come after comments if you want to have the comments first)

The version number https://github.com/andyprice/gfs2-role/blob/main/meta/main.yml#L8C1-L8C28 should be quoted (must be a string value)

https://github.com/andyprice/gfs2-role/tree/main/vars - I don't think you need CentOS_8.N.yml files/links

All of the uses of `ansible.builtin.command` will need a `changed_when` true or false - if the command changes the state of the system, it should use `changed_when: true`, even if the task is conditionally executed with a `when` condition

https://github.com/andyprice/gfs2-role/blob/main/tasks/fs.yml#L19C1-L19C131 - you should wrap this:
```yaml
            fs_create_options: >-
              -D -t {{ gfs2_cluster_name }}:{{ fs.name }}
              -j {{ fs.journals | default(gfs2_default_journals) }}
```
see also https://linux-system-roles.github.io/documentation/howto/working-with-ansible-jinja-code-and-filters.html for tips on other quoting/wrapping issues - you can also use `d(..)` instead of `default(...)` to save a few characters

https://github.com/andyprice/gfs2-role/blob/main/tasks/fs.yml#L3 - `fs` should be `gfs2_fs` since `set_fact` puts variables into the global namespace.  Alternately, rewrite this file using a `block` with `vars` then you can set `fs` as a block scoped variable - you can do that with the other variables you are setting with `set_fact` here e.g.
```yaml
- name: Manage file system configuration
  vars:
    fs: "{{ gfs2_fs_defaults | combine(fs_spec) }}"
    default_resource_name_lv: "{{ fs.vg }}-{{ fs.lv }}"
    resource_name_lv: "{{ fs.resource_name_lv | default(default_resource_name_lv) }}"
    default_group_name_fs: "{{ fs.name }}-group"
    group_name_fs: "{{ fs.group_name_fs | default(default_group_name_fs) }}"
  block:
    - name: Create shared volume group
      include_role:
        name: linux-system-roles.storage
...
```
using `vars` is also nice because the variables are lazily evaluated, which means that in `default_resource_name_lv: "{{ fs.vg }}-{{ fs.lv }}"` the `fs.vg` and `fs.lv` do not have be defined until `default_resource_name_lv` is actually used - this is different than how `set_fact` works which forces immediate evaluation

The test (preferably, the role also) will need some way to remove the `storage` role resources - for an example, see https://github.com/linux-system-roles/snapshot/blob/main/tests/tests_basic.yml#L93
